{{- if .Values.config.toml }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "libgendex.fullname" . }}
  labels:
    {{- include "libgendex.labels" . | nindent 4 }}
data:
  bookjev.toml: |
    {{- .Values.config.toml | nindent 4 }}
{{- end }}
